apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: zc
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: "zc"
          - name: POSTGRES_USER
            value: "zc"
          - name: POSTGRES_PASSWORD
            value: "youcantseeme"
        volumeMounts:
          - name: datadir
            mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: datadir
        hostPath:
          path: /Users/zc/GitHub/zc/datadir/pg
          type: Directory